"""create initial PostgreSQL schema

Revision ID: 001_initial
Revises:
"""
from alembic import op

revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE devices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            imei VARCHAR(20) NOT NULL CONSTRAINT uq_devices_imei UNIQUE,
            name VARCHAR(100),
            model VARCHAR(50) NOT NULL DEFAULT 'B2315P',
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            last_seen_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE raw_archives (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            archive_date DATE NOT NULL,
            imei VARCHAR(20) NOT NULL,
            oss_key VARCHAR(500) NOT NULL,
            record_count INTEGER NOT NULL DEFAULT 0,
            compressed_bytes BIGINT,
            sha256 VARCHAR(64),
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            retry_count INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            uploaded_at TIMESTAMPTZ
        );

        CREATE TABLE health_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            collected_date DATE NOT NULL,
            event_hash VARCHAR(64) NOT NULL,
            imei VARCHAR(20) NOT NULL,
            message_type INTEGER NOT NULL,
            collected_at TIMESTAMPTZ NOT NULL,
            received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            heart_rate INTEGER,
            blood_oxygen INTEGER,
            body_temperature NUMERIC(4,1),
            wrist_temperature NUMERIC(4,1),
            diastolic INTEGER,
            systolic INTEGER,
            steps BIGINT,
            raw_archive_id BIGINT REFERENCES raw_archives(id) ON DELETE SET NULL,
            PRIMARY KEY (id, collected_date),
            CONSTRAINT uq_health_event_date UNIQUE (event_hash, collected_date)
        ) PARTITION BY RANGE (collected_date);

        CREATE TABLE health_records_default PARTITION OF health_records DEFAULT;
        CREATE INDEX ix_health_imei_collected_at ON health_records (imei, collected_at);

        CREATE TABLE ingestion_errors (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            request_id VARCHAR(64) NOT NULL,
            imei VARCHAR(20),
            error_code VARCHAR(50) NOT NULL,
            error_message TEXT NOT NULL,
            payload_excerpt TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS health_records CASCADE")
    op.execute("DROP TABLE IF EXISTS ingestion_errors CASCADE")
    op.execute("DROP TABLE IF EXISTS devices CASCADE")
    op.execute("DROP TABLE IF EXISTS raw_archives CASCADE")
