"""add F9 heartbeat telemetry records

Revision ID: 002_heartbeat_records
Revises: 001_initial
"""

from alembic import op


revision = "002_heartbeat_records"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE heartbeat_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            collected_date DATE NOT NULL,
            event_hash VARCHAR(64) NOT NULL,
            imei VARCHAR(20) NOT NULL,
            message_id SMALLINT NOT NULL DEFAULT 249,
            event_type VARCHAR(30) NOT NULL DEFAULT 'heartbeat',
            collected_at TIMESTAMPTZ NOT NULL,
            received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            battery_type SMALLINT,
            battery_raw_value INTEGER,
            battery_percent NUMERIC(5,2),
            signal_type SMALLINT,
            signal_raw_value INTEGER,
            signal_percent NUMERIC(5,2),
            steps_type SMALLINT,
            steps_value BIGINT,
            raw_hex TEXT NOT NULL,
            raw_archive_id BIGINT REFERENCES raw_archives(id) ON DELETE SET NULL,
            CONSTRAINT uq_heartbeat_event_date UNIQUE (event_hash, collected_date),
            CONSTRAINT ck_heartbeat_message_id CHECK (message_id = 249),
            CONSTRAINT ck_heartbeat_event_type CHECK (event_type = 'heartbeat'),
            CONSTRAINT ck_heartbeat_battery_percent CHECK (
                battery_percent IS NULL OR (battery_percent >= 0 AND battery_percent <= 100)
            ),
            CONSTRAINT ck_heartbeat_signal_percent CHECK (
                signal_percent IS NULL OR (signal_percent >= 0 AND signal_percent <= 100)
            )
        );
        CREATE INDEX ix_heartbeat_imei_collected_at
            ON heartbeat_records (imei, collected_at DESC);
        CREATE INDEX ix_heartbeat_event_hash
            ON heartbeat_records (event_hash);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS heartbeat_records CASCADE")
