"""add alarm, location, sleep, and device configuration event tables

Revision ID: 004_device_events
Revises: 003_sync_identity_sequences
"""

from alembic import op


revision = "004_device_events"
down_revision = "003_sync_identity_sequences"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE device_alarms (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT NOT NULL
                REFERENCES devices(id) ON DELETE CASCADE,
            event_hash VARCHAR(64) NOT NULL,
            collected_date DATE NOT NULL,
            imei VARCHAR(20) NOT NULL,
            message_id SMALLINT NOT NULL,
            collected_at TIMESTAMPTZ NOT NULL,
            received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            alarm_group INTEGER,
            alarm_mask INTEGER,
            alarm_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
            sensor_type INTEGER,
            threshold_direction INTEGER,
            measured_value NUMERIC,
            sensor_values JSONB,
            status VARCHAR(16) NOT NULL DEFAULT 'pending',
            acknowledged_at TIMESTAMPTZ,
            parse_version VARCHAR(16),
            raw_hex TEXT NOT NULL,
            raw_archive_id BIGINT
                REFERENCES raw_archives(id) ON DELETE SET NULL,
            CONSTRAINT uq_alarm_event_date UNIQUE (event_hash, collected_date)
        );
        CREATE INDEX ix_alarm_imei_collected_at
            ON device_alarms (imei, collected_at DESC);
        CREATE INDEX ix_alarm_status_collected_at
            ON device_alarms (status, collected_at DESC);

        CREATE TABLE location_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT NOT NULL
                REFERENCES devices(id) ON DELETE CASCADE,
            event_hash VARCHAR(64) NOT NULL,
            collected_date DATE NOT NULL,
            imei VARCHAR(20) NOT NULL,
            message_id SMALLINT NOT NULL,
            collected_at TIMESTAMPTZ NOT NULL,
            received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            source VARCHAR(16) NOT NULL,
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            north_south CHAR(1),
            east_west CHAR(1),
            position_status CHAR(1),
            position_valid BOOLEAN,
            coordinate_system VARCHAR(16),
            precision_digits SMALLINT,
            cells JSONB,
            wifi_access_points JSONB,
            beacon_groups JSONB,
            resolution_status VARCHAR(16) NOT NULL DEFAULT 'direct',
            raw_hex TEXT NOT NULL,
            raw_archive_id BIGINT
                REFERENCES raw_archives(id) ON DELETE SET NULL,
            CONSTRAINT uq_location_event_date UNIQUE (event_hash, collected_date)
        );
        CREATE INDEX ix_location_imei_collected_at
            ON location_records (imei, collected_at DESC);

        CREATE TABLE sleep_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT NOT NULL
                REFERENCES devices(id) ON DELETE CASCADE,
            event_hash VARCHAR(64) NOT NULL,
            collected_date DATE NOT NULL,
            imei VARCHAR(20) NOT NULL,
            message_id SMALLINT NOT NULL,
            collected_at TIMESTAMPTZ NOT NULL,
            received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            start_at TIMESTAMPTZ,
            end_at TIMESTAMPTZ,
            duration_minutes SMALLINT,
            sleep_stage SMALLINT,
            raw_hex TEXT NOT NULL,
            raw_archive_id BIGINT
                REFERENCES raw_archives(id) ON DELETE SET NULL,
            CONSTRAINT uq_sleep_event_date UNIQUE (event_hash, collected_date),
            CONSTRAINT ck_sleep_end_after_start CHECK (
                start_at IS NULL OR end_at IS NULL OR end_at >= start_at
            ),
            CONSTRAINT ck_sleep_duration_nonnegative CHECK (
                duration_minutes IS NULL OR duration_minutes >= 0
            )
        );
        CREATE INDEX ix_sleep_imei_collected_at
            ON sleep_records (imei, collected_at DESC);

        CREATE TABLE device_config_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT NOT NULL
                REFERENCES devices(id) ON DELETE CASCADE,
            event_hash VARCHAR(64) NOT NULL,
            collected_date DATE NOT NULL,
            imei VARCHAR(20) NOT NULL,
            message_id SMALLINT NOT NULL DEFAULT 233,
            collected_at TIMESTAMPTZ NOT NULL,
            received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            location_modified BOOLEAN,
            location_interval_minutes SMALLINT,
            health_modified BOOLEAN,
            health_interval_minutes SMALLINT,
            timestamp_source VARCHAR(16) NOT NULL DEFAULT 'received_at',
            raw_hex TEXT NOT NULL,
            raw_archive_id BIGINT
                REFERENCES raw_archives(id) ON DELETE SET NULL,
            CONSTRAINT uq_device_config_event_date UNIQUE (event_hash, collected_date),
            CONSTRAINT ck_device_config_message_id CHECK (message_id = 233),
            CONSTRAINT ck_device_config_timestamp_source CHECK (
                timestamp_source = 'received_at'
            )
        );
        CREATE INDEX ix_device_config_imei_collected_at
            ON device_config_snapshots (imei, collected_at DESC);
        """
    )


def downgrade() -> None:
    # Drop in reverse dependency/order so a downgrade is safe even when
    # PostgreSQL has retained indexes and foreign-key metadata.
    op.execute("DROP TABLE IF EXISTS device_config_snapshots CASCADE")
    op.execute("DROP TABLE IF EXISTS sleep_records CASCADE")
    op.execute("DROP TABLE IF EXISTS location_records CASCADE")
    op.execute("DROP TABLE IF EXISTS device_alarms CASCADE")
