"""add persistent downlink command queue

Revision ID: 005_device_commands
Revises: 004_device_events
"""

from alembic import op


revision = "005_device_commands"
down_revision = "004_device_events"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE device_commands (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT NOT NULL
                REFERENCES devices(id) ON DELETE CASCADE,
            imei VARCHAR(20) NOT NULL,
            command_type VARCHAR(32) NOT NULL,
            message_id SMALLINT NOT NULL,
            subtype SMALLINT,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            frame_hex TEXT NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'pending',
            attempts INTEGER NOT NULL DEFAULT 0,
            max_attempts INTEGER NOT NULL DEFAULT 3,
            available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            claimed_at TIMESTAMPTZ,
            claim_expires_at TIMESTAMPTZ,
            claimed_by VARCHAR(100),
            sent_at TIMESTAMPTZ,
            acknowledged_at TIMESTAMPTZ,
            feedback_message_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
            last_error TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_device_commands_status CHECK (
                status IN ('pending', 'claimed', 'sent', 'acknowledged', 'failed', 'expired')
            ),
            CONSTRAINT ck_device_commands_attempts_nonnegative CHECK (attempts >= 0),
            CONSTRAINT ck_device_commands_max_attempts_positive CHECK (max_attempts > 0),
            CONSTRAINT ck_device_commands_message_id CHECK (message_id IN (23, 206)),
            CONSTRAINT ck_device_commands_subtype CHECK (
                (message_id = 23 AND subtype IS NULL)
                OR (message_id = 206 AND subtype IN (1, 2, 7, 8, 25, 32))
            )
        );
        CREATE INDEX ix_device_commands_imei_status
            ON device_commands (imei, status, available_at);
        CREATE INDEX ix_device_commands_pending
            ON device_commands (status, available_at, created_at);
        CREATE INDEX ix_device_commands_imei_created_at
            ON device_commands (imei, created_at DESC);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS device_commands CASCADE")
