"""add browser roles, users, and IMEI device bindings

Revision ID: 006_auth_device_bindings
Revises: 005_device_commands
"""

from alembic import op


revision = "006_auth_device_bindings"
down_revision = "005_device_commands"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE roles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(32) NOT NULL CONSTRAINT uq_roles_name UNIQUE
        );

        CREATE TABLE users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(100) NOT NULL CONSTRAINT uq_users_username UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            display_name VARCHAR(100),
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX ix_users_role_id ON users(role_id);

        CREATE TABLE user_device_bindings (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            device_id BIGINT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (user_id, device_id)
        );
        CREATE INDEX ix_user_device_bindings_device_id
            ON user_device_bindings(device_id);

        INSERT INTO roles (name) VALUES ('admin'), ('operator'), ('viewer')
        ON CONFLICT (name) DO NOTHING;
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS user_device_bindings CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TABLE IF EXISTS roles CASCADE")
