"""add administrator-managed alarm rules

Revision ID: 007_alarm_rules
Revises: 006_auth_device_bindings
"""

from alembic import op


revision = "007_alarm_rules"
down_revision = "006_auth_device_bindings"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE alarm_rules (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL CONSTRAINT uq_alarm_rules_name UNIQUE,
            alarm_type VARCHAR(32) NOT NULL,
            threshold NUMERIC,
            direction VARCHAR(4),
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_alarm_rules_direction CHECK (direction IS NULL OR direction IN ('gte', 'lte'))
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS alarm_rules CASCADE")
